# Generated by Django 6.0.3 on 2026-03-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_servicerequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
