# Generated by Django 6.0.3 on 2026-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_servicerequest_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
