# Generated by Django 6.0.3 on 2026-03-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_servicerequest_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
