# Generated by Django 6.0.3 on 2026-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_servicerequest_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
