# Generated by Django 6.0.3 on 2026-03-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_images/'),
        ),
    ]
