# Generated by Django 6.0.3 on 2026-03-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_servicerequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='created_at',
            new_name='requested_at',
        ),
    ]
