# Generated by Django 6.0.3 on 2026-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_created_at_servicerequest_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
