# Generated by Django 6.0.3 on 2026-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_service_description_delete_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='provider_images/'),
        ),
    ]
