# Generated by Django 6.0.3 on 2026-03-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='service',
        ),
        migrations.AddField(
            model_name='provider',
            name='services',
            field=models.ManyToManyField(to='services.service'),
        ),
    ]
