# Generated by Django 6.0.3 on 2026-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_provider_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
    ]
