# Generated by Django 6.0.3 on 2026-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_provider_profile_image_alter_provider_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='availability',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='credentials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='portfolio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
