# Generated by Django 6.0.3 on 2026-06-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_approvalrecord_servicecataloguelog_systemreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
