# Generated by Django 6.0.3 on 2026-03-22 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_servicerequest_payment_status_and_more'),
        ('services', '0009_alter_service_description_delete_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.provider'),
        ),
    ]
