# Generated by Django 6.0.3 on 2026-06-19 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_servicerequest_rating_servicerequest_review'),
        ('services', '0012_provider_approval_status_provider_availability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='complaint_resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='complaint_status',
            field=models.CharField(choices=[('none', 'No Complaint'), ('open', 'Open'), ('resolved', 'Resolved')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='decline_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Not recorded'), ('cash', 'Cash'), ('mpesa', 'M-Pesa')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['service', 'location'], name='requests_se_service_124598_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'payment_status'], name='requests_se_status_a1263e_idx'),
        ),
    ]
