# Generated by Django 6.0.3 on 2026-06-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_paymentrecord_providerselection_searchhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='service_request',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='payment_record',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='performed_by',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='requests_se_service_124598_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='requests_se_status_a1263e_idx',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
        migrations.DeleteModel(
            name='TransactionLog',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='mpesa_code',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='payment_recorded_at',
        ),
    ]
